URLS = {
'http://buildbot/json': """
        {
            "builders": {"failingBuilderA": {"basedir": "ba",
                                   "cachedBuilds": [28, 29, 30],
                                   "category": null,
                                   "currentBuilds": [],
                                   "pendingBuilds": [],
                                   "slaves": ["johnbrown"],
                                   "state": "idle"},
                         "failingBuilderB": {"basedir": "bb",
                                   "cachedBuilds": [30, 31, 32],
                                   "category": null,
                                   "currentBuilds": [],
                                   "pendingBuilds": [],
                                   "slaves": ["johnbrown"],
                                   "state": "idle"},
                        "passingBuilderX": {"basedir": "passingBuilderX",
                                            "cachedBuilds": [21, 22],
                                            "category": null,
                                            "currentBuilds": [],
                                            "pendingBuilds": [],
                                            "slaves": ["bs1.jacobian.org"],
                                            "state": "idle"}
                        }

        }
        """,

'http://buildbot/json/builders/failingBuilderA/builds/-1': """
        {"blame": ["Ales Zoulek <ales.zoulek@gmail.com>"],
         "builderName": "failingBuilderA",
         "currentStep": null,
         "eta": null,
         "number": 30,
         "properties": [["branch", null, "Build"],
                        ["buildername", "failingBuilderA", "Builder"],
                        ["buildnumber", 30, "Build"],
                        ["project", "solid", "Build"],
                        ["repository", "hg/solid", "Build"],
                        ["revision",
                         "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                         "Build"],
                        ["scheduler", "solid", "Scheduler"],
                        ["slavename", "johnbrown", "BuildSlave"]],
         "reason": "scheduler",
         "results": 2,
         "slave": "johnbrown",
         "sourceStamp": {"branch": null,
                         "changes": [{"at": "Wed 24 Nov 2010 14:52:30",
                                      "branch": null,
                                      "category": null,
                                      "comments": "solid.libs.jinja2 removed",
                                      "files": [{"name": "solid/libs/jinja2.py",
                                                 "url": null},
                                                {"name": "solid/libs/proc.py",
                                                 "url": null},
                                                {"name": "solid/mailing/models.py",
                                                 "url": null}],
                                      "number": 76,
                                      "project": "solid",
                                      "properties": [],
                                      "repository": "hg/solid",
                                      "rev": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revlink": "",
                                      "when": 1290606750.101381,
                                      "who": "Roman Krejcik <krejcik@i3.cz>"}],
                         "hasPatch": false,
                         "project": "solid",
                         "repository": "hg/solid",
                         "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7"},
         "steps": [{"eta": null,
                    "expectations": [["output", 201435, null]],
                    "isFinished": true,
                    "isStarted": true,
                    "name": "project 1 test",
                    "results": [2, ["project 1 test"]],
                    "statistics": {},
                    "step_number": 0,
                    "text": ["tested", "failed"],
                    "times": [1290607051.566786, 1290607063.803715],
                    "urls": {}}],
         "text": ["failed", "project 1 test"],
         "times": [1290607051.566614, 1290607063.804476]}
    """,

'http://buildbot/json/builders/failingBuilderB/builds/-1': """
        {"blame": ["Ales Zoulek <ales.zoulek@gmail.com>"],
         "builderName": "failingBuilderB",
         "currentStep": null,
         "eta": null,
         "number": 30,
         "properties": [["branch", null, "Build"],
                        ["buildername", "failingBuilderB", "Builder"],
                        ["buildnumber", 30, "Build"],
                        ["project", "solid", "Build"],
                        ["repository", "hg/solid", "Build"],
                        ["revision",
                         "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                         "Build"],
                        ["scheduler", "solid", "Scheduler"],
                        ["slavename", "johnbrown", "BuildSlave"]],
         "reason": "scheduler",
         "results": 2,
         "slave": "johnbrown",
         "sourceStamp": {"branch": null,
                         "changes": [{"at": "Wed 24 Nov 2010 14:52:30",
                                      "branch": null,
                                      "category": null,
                                      "comments": "solid.libs.jinja2 removed",
                                      "files": [{"name": "solid/libs/jinja2.py",
                                                 "url": null},
                                                {"name": "solid/libs/proc.py",
                                                 "url": null},
                                                {"name": "solid/mailing/models.py",
                                                 "url": null}],
                                      "number": 76,
                                      "project": "solid",
                                      "properties": [],
                                      "repository": "hg/solid",
                                      "rev": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revlink": "",
                                      "when": 1290606750.101381,
                                      "who": "Roman Krejcik <krejcik@i3.cz>"}],
                         "hasPatch": false,
                         "project": "solid",
                         "repository": "hg/solid",
                         "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7"},
         "steps": [{"eta": null,
                    "expectations": [["output", 201435, null]],
                    "isFinished": true,
                    "isStarted": true,
                    "name": "project 2 test",
                    "results": [2, ["project 2 test"]],
                    "statistics": {},
                    "step_number": 0,
                    "text": ["tested", "failed"],
                    "times": [1290607051.566786, 1290607063.803715],
                    "urls": {}}],
         "text": ["failed", "project 2 test"],
         "times": [1290607051.566614, 1290607063.804476]}
    """,



'http://buildbot/json/builders/passingBuilderX/builds/-1': """
    {"blame": ["Alex",
               "Honza_Kral",
               "ramiro",
               "russellm"],
     "builderName": "1.2.X-python2.4-sqlite3.X",
     "currentStep": null,
     "eta": null,
     "number": 13,
     "properties": [["branch", "1.2.X", "Build"],
                    ["buildername", "1.2.X-python2.4-sqlite3.X", "Builder"],
                    ["buildnumber", 13, "Build"],
                    ["got_revision", "14695", "Source"],
                    ["project", "Django", "Build"],
                    ["python2.4", "python2.4", "BuildSlave"],
                    ["python2.5", "python2.5", "BuildSlave"],
                    ["python2.6", "python2.6", "BuildSlave"],
                    ["repository",
                     "http://code.djangoproject.com/svn/django",
                     "Build"],
                    ["revision", "14695", "Build"],
                    ["scheduler", "1.2.X", "Scheduler"],
                    ["slavename", "bs1.jacobian.org", "BuildSlave"],
                    ["warnings-count", 0, "WarningCountingShellCommand"]],
     "reason": "scheduler",
     "results": 0,
     "slave": "bs1.jacobian.org",
     "sourceStamp": {"branch": "1.2.X",
                     "changes": [{"at": "Fri 12 Nov 2010 10:52:09",
                                  "branch": "1.2.X",
                                  "category": null,
                                  "comments": "[1.2.X] Backport of r14545 from trunk. Fixed a multiple_database test case that was failing in Oracle due to forced table name capitalization.  The test case now matches the style used by the raw_query tests.",
                                  "files": [{"name": "", "url": null},
                                            {"name": "tests/regressiontests/multiple_database/tests.py",
                                             "url": null}],
                                  "number": 82,
                                  "project": "Django",
                                  "properties": [],
                                  "repository": "http://code.djangoproject.com/svn/django",
                                  "rev": "14546",
                                  "revision": "14546",
                                  "revlink": "http://code.djangoproject.com/changeset/14546",
                                  "when": 1289587929.632855,
                                  "who": "ikelly"}],
                     "hasPatch": false,
                     "project": "Django",
                     "repository": "http://code.djangoproject.com/svn/django",
                     "revision": "14695"},
     "steps": [{"eta": null,
                "expectations": [["output", 12321, null]],
                "isFinished": true,
                "isStarted": true,
                "name": "svn checkout",
                "results": [0, []],
                "statistics": {},
                "step_number": 0,
                "text": ["update", "r14695"],
                "times": [1290632470.721961, 1290632488.859646],
                "urls": {}},
               {"eta": null,
                "expectations": [],
                "isFinished": true,
                "isStarted": true,
                "name": "virtualenv download",
                "results": [0, []],
                "statistics": {},
                "step_number": 1,
                "text": ["downloading", "to", "virtualenv.py"],
                "times": [1290632488.861061, 1290632489.394985],
                "urls": {}}],
     "text": ["build", "successful"],
     "times": [1290632470.720937, 1290632903.109146]}
"""

}

