URLS = {
'http://buildbot/json': """
        {
            "builders": {"builderA": {"basedir": "ba",
                                   "cachedBuilds": [28, 29, 30],
                                   "category": null,
                                   "currentBuilds": [],
                                   "pendingBuilds": [],
                                   "slaves": ["johnbrown"],
                                   "state": "idle"},
                         "builderB": {"basedir": "bb",
                                   "cachedBuilds": [30, 31, 32],
                                   "category": null,
                                   "currentBuilds": [],
                                   "pendingBuilds": [],
                                   "slaves": ["johnbrown"],
                                   "state": "idle"}
                        }
        }
        """,

'http://buildbot/json/builders/builderA/builds/-1': """
        {"blame": ["Ales Zoulek <ales.zoulek@gmail.com>"],
         "builderName": "builderA",
         "currentStep": null,
         "eta": null,
         "number": 30,
         "properties": [["branch", null, "Build"],
                        ["buildername", "builderA", "Builder"],
                        ["buildnumber", 30, "Build"],
                        ["project", "solid", "Build"],
                        ["repository", "hg/solid", "Build"],
                        ["revision",
                         "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                         "Build"],
                        ["scheduler", "solid", "Scheduler"],
                        ["slavename", "johnbrown", "BuildSlave"]],
         "reason": "scheduler",
         "results": 2,
         "slave": "johnbrown",
         "sourceStamp": {"branch": null,
                         "changes": [{"at": "Wed 24 Nov 2010 14:52:30",
                                      "branch": null,
                                      "category": null,
                                      "comments": "solid.libs.jinja2 removed",
                                      "files": [{"name": "solid/libs/jinja2.py",
                                                 "url": null},
                                                {"name": "solid/libs/proc.py",
                                                 "url": null},
                                                {"name": "solid/mailing/models.py",
                                                 "url": null}],
                                      "number": 76,
                                      "project": "solid",
                                      "properties": [],
                                      "repository": "hg/solid",
                                      "rev": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revlink": "",
                                      "when": 1290606750.101381,
                                      "who": "Roman Krejcik <krejcik@i3.cz>"}],
                         "hasPatch": false,
                         "project": "solid",
                         "repository": "hg/solid",
                         "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7"},
         "steps": [{"eta": null,
                    "expectations": [["output", 201435, null]],
                    "isFinished": true,
                    "isStarted": true,
                    "name": "project 1 test",
                    "results": [2, ["project 1 test"]],
                    "statistics": {},
                    "step_number": 0,
                    "text": ["tested", "failed"],
                    "times": [1290607051.566786, 1290607063.803715],
                    "urls": {}}],
         "text": ["failed", "project 1 test"],
         "times": [1290607051.566614, 1290607063.804476]}
    """,

'http://buildbot/json/builders/builderB/builds/-1': """
        {"blame": ["Ales Zoulek <ales.zoulek@gmail.com>"],
         "builderName": "builderB",
         "currentStep": null,
         "eta": null,
         "number": 30,
         "properties": [["branch", null, "Build"],
                        ["buildername", "builderB", "Builder"],
                        ["buildnumber", 30, "Build"],
                        ["project", "solid", "Build"],
                        ["repository", "hg/solid", "Build"],
                        ["revision",
                         "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                         "Build"],
                        ["scheduler", "solid", "Scheduler"],
                        ["slavename", "johnbrown", "BuildSlave"]],
         "reason": "scheduler",
         "results": 2,
         "slave": "johnbrown",
         "sourceStamp": {"branch": null,
                         "changes": [{"at": "Wed 24 Nov 2010 14:52:30",
                                      "branch": null,
                                      "category": null,
                                      "comments": "solid.libs.jinja2 removed",
                                      "files": [{"name": "solid/libs/jinja2.py",
                                                 "url": null},
                                                {"name": "solid/libs/proc.py",
                                                 "url": null},
                                                {"name": "solid/mailing/models.py",
                                                 "url": null}],
                                      "number": 76,
                                      "project": "solid",
                                      "properties": [],
                                      "repository": "hg/solid",
                                      "rev": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7",
                                      "revlink": "",
                                      "when": 1290606750.101381,
                                      "who": "Roman Krejcik <krejcik@i3.cz>"}],
                         "hasPatch": false,
                         "project": "solid",
                         "repository": "hg/solid",
                         "revision": "565c4ceadfea6dabd80e615485e2b5b5418090e7"},
         "steps": [{"eta": null,
                    "expectations": [["output", 201435, null]],
                    "isFinished": true,
                    "isStarted": true,
                    "name": "project 2 test",
                    "results": [2, ["project 2 test"]],
                    "statistics": {},
                    "step_number": 0,
                    "text": ["tested", "failed"],
                    "times": [1290607051.566786, 1290607063.803715],
                    "urls": {}}],
         "text": ["failed", "project 2 test"],
         "times": [1290607051.566614, 1290607063.804476]}
    """
}

